#!/bin/sh
set -xe

qemu-img create -f qcow2 windows.img 100G

# No VNC
novnc_server --vnc localhost:5901 &
cloudflared tunnel --url http://localhost:8080 --hostname trycloudflare.com &



# Without Virt-IO (OK for Live ISO)
# qemu-system-x86_64 \
#     -m 2048M \
#     -nographic \
#     -vnc :1 \
#     -boot order=d \
#     \
#     -drive file=windows.img,media=disk,format=raw \
#     -drive file=windows.iso,media=cdrom


# Boot (for installer)
qemu-system-x86_64 \
    -m 12G \
    -vnc :1
    -nographic -vnc :1 \
    -machine q35 \
    -drive file="windows.iso",media=cdrom \
    -drive file="virtio-win.iso",media=cdrom \
    -usb -device usb-kbd \
    -device usb-tablet \
    -rtc base=localtime \
    -smp sockets=1,cores=8,threads=2 \
        -k en-us \
        -net nic,model=virtio \
        -net user,hostfwd=tcp::4444-:4444 \
        -drive file=windows.img,media=disk,if=virtio
        #-enable-kvm \

    
